In [1]:
import pymc,imp
import numpy as np
from pymc import MAP

allAIC = np.zeros((10))
allBIC = np.zeros((10))
i=0

Basic model - correlated random walk
====================
parameters
-------------- 
$\rho_m$ - Cauchy parameter that specifies degree of correlation between successive steps

In [2]:
import corRandomWalk
imp.reload(corRandomWalk)

CRW = MAP(corRandomWalk)
CRW.fit()

print(CRW.AIC)
print(CRW.BIC)
print('--------')
print(CRW.rho_m.value) 
allAIC[i]=CRW.AIC
allBIC[i]=CRW.BIC
i=i+1

-16427.431791779964
-16419.6441641
--------
0.9324389388365363


Environment model
==========
parameters
-----------
$\rho_m$ - Cauchy parameter that specifies degree of correlation between successive steps

$\rho_e$ - parameter that relates assumed environmental features to heading

$\beta$ - relative weighting of Cauchy distributions

In [3]:
import environment
imp.reload(environment)
E = MAP(environment)
E.fit()
print(E.AIC)
print(E.BIC)
print('--------')
print(E.rho_m.value) 
print(E.beta.value)

allAIC[i]=E.AIC
allBIC[i]=E.BIC
i=i+1

-18197.86619617906
-18182.2909408
--------
0.9356733102039562
0.1573921923349769


Social models
========

All models use the following parameters

$\rho_s$ - bias in Caucy distribution (how predictive of movement step is social vector)

$\rho_m$ - Cauchy parameter that specifies degree of correlation between successive steps

$\rho_e$ - parameter that relates assumed environmental features to heading

$\alpha$ - relative weighting of social to env/persistence distributions

$\beta$ - relative weighting of env and persistence distributions


Social interaction rules
=============

Model 1
--------

Social vector is the average of relative positions to all neighbours within a constant interaction range

$I_D$ is the maximum interaction distance

$I_A$ is the maximum interaction angle either side of the centre of the animal

$I_R$ is the zone within which neighbours are ignored



In [4]:
import constantModel
imp.reload(constantModel)
CM = MAP(constantModel)
CM.fit()
print(CM.AIC)
print(CM.BIC)
print('--------')
print(CM.rho_s.value)
print(CM.alpha.value) 
print(CM.beta.value) 
print('--------')
print(CM.interaction_length.value)
print(CM.interaction_angle.value)
print(CM.ignore_length.value)

allAIC[i]=CM.AIC
allBIC[i]=CM.BIC
i=i+1

-19600.979511248424
-19554.2537452
--------
0.9394593815727138
0.35717319839771045
0.14021750465373115
--------
10.144491732939489
0.2518123574185419
1.3062288981961772


Model 2
--------

Social vector is the weighted average of position of a point each neighbour is heading towards within a constant interaction range

$I_D$ is the maximum interaction distance

$I_A$ is the maximum interaction angle either side of the centre of the animal

$I_R$ is the zone within which neighbours are ignored

$Al_W$ is the relative weight of attraction and alignment




In [5]:
import constantModelAlign
import imp
import pymc 
from pymc import MAP
imp.reload(constantModelAlign)

CMA = MAP(constantModelAlign)
CMA.fit()
print(CMA.AIC)
print(CMA.BIC)
print('--------')
print(CMA.rho_s.value)
print(CMA.alpha.value) 
print(CMA.beta.value) 
print('--------')
print(CMA.attract_length.value)
print(CMA.attract_angle.value)
print(CMA.align_weight.value)
print(CMA.ignore_length.value)

allAIC[i]=CMA.AIC
allBIC[i]=CMA.BIC
i=i+1

-19656.39632010461
-19601.8829264
--------
0.9394953378206546
0.3719546022212312
0.13660503082959588
--------
10.125587866054083
0.25180489623295826
0.5754751444460896
1.2571125473283877


Model 3
--------

Social vector is the average of relative positions to all neighbours weighted according to an exponential decay

$I_A$ is the maximum attraction angle either side of the centre of the animal

The weighting given to each neighbour is 

$\omega_i =  \exp\left(-\left(\frac{D}{I_D}\right)^\gamma\right)$

$\gamma$ decay exponent

$I_D$ peak distance



In [6]:
import decayModel
imp.reload(decayModel)
DM = MAP(decayModel)
DM.fit()
print(DM.AIC)
print(DM.BIC)
print('--------')
print(DM.rho_s.value)
print(DM.alpha.value) 
print(DM.beta.value) 
print('--------')
print(DM.decay_exponent.value)
print(DM.interaction_length.value)
print(DM.interaction_angle.value)
print(DM.ignore_length.value)

allAIC[i]=DM.AIC
allBIC[i]=DM.BIC
i=i+1

-19604.022824004656
-19549.5094303
--------
0.9394726959317081
0.35075891591188657
0.14173589180198376
--------
19.26101851591356
8.137958350776941
0.25139681086448773
1.285012351222953


Model 4
--------

Social vector is the weighted average of relative positions to a point each neighbour is heading towards (i.e. includes alignment force) weighted with an exponential decay according to distance



$I_A$ is the maximum attraction angle either side of the centre of the animal


$Al_W$ is the weight of attraction and alignment

The weighting given to each neighbour is 

$\omega_i =  \exp\left(-\left(\frac{D}{I_D}\right)^\gamma\right)$

$\gamma$ decay exponent

$I_D$ is the peak influence distance


In [7]:
import decayModelAlign

import imp
imp.reload(decayModelAlign)
DMA = MAP(decayModelAlign)
DMA.fit()
print(DMA.AIC)
print(DMA.BIC)
print('--------')
print(DMA.rho_s.value)
print(DMA.alpha.value) 
print(DMA.beta.value) 
print('--------')
print(DMA.attract_exponent.value)
print(DMA.attract_length.value)
print(DMA.attract_angle.value)
print(DMA.ignore_length.value)
print(DMA.align_weight.value)

allAIC[i]=DMA.AIC
allBIC[i]=DMA.BIC
i=i+1

-19715.77351286013
-19653.4724915
--------
0.9396529725088002
0.3870379791643967
0.13673084835299582
--------
9.272935648814755
4.994414655997313
0.27642330874196225
1.3065421032118985
0.7659181663834961


Model 5
--------

Social vector is the average of relative positions to all neighbours within a network interaction range

$I_D$ is the maximum number of neighbours

$I_A$ is the maximum interaction angle either side of the centre of the animal



In [8]:
import networkModel
import imp
imp.reload(networkModel)

networkModel.netcount=1

NM = MAP(networkModel)
NM.fit()#method ='fmin', iterlim=100000, tol=.000001)
print('==== 1 neighbour ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print(NM.beta.value) 
print('--------')
print(NM.interaction_angle.value)

allAIC[i]=NM.AIC
allBIC[i]=NM.BIC
i=i+1
networkModel.netcount=2

NM = MAP(networkModel)
NM.fit()#method ='fmin', iterlim=100000, tol=.000001)
print('==== 2 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print(NM.beta.value) 
print('--------')
print(NM.interaction_angle.value)


networkModel.netcount=3

NM = MAP(networkModel)
NM.fit()#method ='fmin', iterlim=100000, tol=.000001)
print('==== 3 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print(NM.beta.value) 
print('--------')
print(NM.interaction_angle.value)

networkModel.netcount=4

NM = MAP(networkModel)
NM.fit()#method ='fmin', iterlim=100000, tol=.000001)
print('==== 4 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print(NM.beta.value) 
print('--------')
print(NM.interaction_angle.value)

networkModel.netcount=5

NM = MAP(networkModel)
NM.fit()#method ='fmin', iterlim=100000, tol=.000001)
print('==== 5 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print(NM.beta.value) 
print('--------')
print(NM.interaction_angle.value)


==== 1 neighbour ====
-19380.51330613022
-19333.7875401
--------
0.9386337195765454
0.22016181286181535
0.15109180255233964
--------
0.2805550081635955
==== 2 neighbours ====
-19335.112405915723
-19288.3866399
--------
0.9383295046954787
0.21565209035863264
0.14461121771575428
--------
0.3085861369503283
==== 3 neighbours ====
-19254.010103820834
-19207.2843378
--------
0.9381297369735669
0.21459830548952757
0.14177506033238993
--------
0.3085779805248097
==== 4 neighbours ====
-19153.563599843623
-19106.8378338
--------
0.9378656663283979
0.20663960278785207
0.14047402552993804
--------
0.308531770795296
==== 5 neighbours ====
-19089.75940479285
-19043.0336388
--------
0.9377086572476303
0.20001774068191538
0.14019140183693643
--------
0.3085809296441188


Model 6
--------

Social vector is the average of relative positions to all neighbours and their headings within a network interaction range

$I_D$ is the maximum number of neighbours

$I_A$ is the maximum interaction angle either side of the centre of the animal



In [10]:
import networkModelAlign
imp.reload(networkModelAlign)
networkModelAlign.netcount=1

NM = MAP(networkModelAlign)
NM.fit(method ='fmin', iterlim=100000, tol=.000001)
print('==== 1 neighbour ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print('--------')
print(NM.interaction_angle.value)

allAIC[i]=NM.AIC
allBIC[i]=NM.BIC
i=i+1

networkModelAlign.netcount=2

NM = MAP(networkModelAlign)
NM.fit(method ='fmin', iterlim=100000, tol=.000001)
print('==== 2 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print('--------')
print(NM.interaction_angle.value)


networkModelAlign.netcount=3

NM = MAP(networkModelAlign)
NM.fit(method ='fmin', iterlim=100000, tol=.000001)
print('==== 3 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print('--------')
print(NM.interaction_angle.value)


networkModelAlign.netcount=4

NM = MAP(networkModelAlign)
NM.fit(method ='fmin', iterlim=100000, tol=.000001)
print('==== 4 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print('--------')
print(NM.interaction_angle.value)


networkModelAlign.netcount=5

NM = MAP(networkModelAlign)
NM.fit(method ='fmin', iterlim=100000, tol=.000001)
print('==== 5 neighbours ====')
print(NM.AIC)
print(NM.BIC)
print('--------')
print(NM.rho_s.value)
print(NM.alpha.value) 
print('--------')
print(NM.interaction_angle.value)


==== 1 neighbour ====
-19473.817036042066
-19419.3036424
--------
0.9387376717386503
0.23569999931373675
--------
0.2842569047789764
==== 2 neighbours ====
-19377.293132165316
-19322.7797385
--------
0.9384704167405904
0.2324102395552717
--------
0.3084273312704709
==== 3 neighbours ====
-19283.73643996288
-19229.2230463
--------
0.9381347666289896
0.22233633184923407
--------
0.3086226590579279
==== 4 neighbours ====
-19174.286014528618
-19119.7726209
--------
0.9380682600749892
0.214447033958243
--------
0.30865339853081253
==== 5 neighbours ====
-19105.637090707543
-19051.123697
--------
0.9374584746842134
0.20762382362950976
--------
0.3087643532373062


In [ ]:
print(DMA.angle_exponent.value)

In [11]:
allAIC

array([-16427.43179178, -18197.86619618, -19600.97951125, -19656.3963201 ,
       -19604.022824  , -19715.77351286, -19380.51330613, -19473.81703604,
            0.        ,      0.        ])

In [12]:
allBIC


array([-16419.64416411, -18182.29094085, -19554.25374525, -19601.88292644,
       -19549.50943034, -19653.47249153, -19333.78754013, -19419.30364238,
            0.        ,      0.        ])

In [13]:
np.argsort(allBIC)

array([5, 3, 2, 4, 7, 6, 1, 0, 8, 9])

In [14]:
np.argsort(allAIC)

array([5, 3, 4, 2, 7, 6, 1, 0, 8, 9])

In [16]:
allAIC[np.argsort(allAIC)]

array([-19715.77351286, -19656.3963201 , -19604.022824  , -19600.97951125,
       -19473.81703604, -19380.51330613, -18197.86619618, -16427.43179178,
            0.        ,      0.        ])

In [27]:
aa = allAIC - np.max(allAIC[0:8])

In [33]:
for p in np.argsort(np.argsort(allAIC)): print(p+1)

8
7
4
2
3
1
6
5
9
10


In [32]:
aa = allBIC - np.max(allBIC[0:8])
for p in aa: print(p)
for p in np.argsort(np.argsort(allBIC)): print(p+1)

0.0
-1762.64677673
-3134.60958114
-3182.23876233
-3129.86526623
-3233.82832742
-2914.14337602
-2999.65947826
16419.6441641
16419.6441641
8
7
3
2
4
1
6
5
9
10
